варіант для таблетки та декстопу
VVr17/group-project-ice-cream pull request #30
Opened 2022-06-25 20:24 UTC by DimaDibchak

2022-06-25 20:49 UTC, VVr17 commented on src/partials/hero.html
> +<div class="container hero--container">
hero__container (нижнее подчеркивание)

2022-06-25 21:23 UTC, VVr17 requested changes
и исправить мороженку.

2022-06-26 07:30 UTC, DimaDibchak commented on src/partials/hero.html
> +<div class="container hero--container">
Я якщо можна, так би це і залишив.  Це аля модіфікатор

2022-06-26 07:33 UTC, VVr17 commented on src/partials/hero.html
> +<div class="container hero--container">
ok :)

2022-06-26 07:33 UTC, VVr17 approved these changes

2022-06-26 07:33 UTC, merged